export const BRAZIL_SATATES = [
    { estado: 'Acre', acronym: 'AC' },
    { estado: 'Alagoas', acronym: 'AL' },
    { estado: 'Amapá', acronym: 'AP' },
    { estado: 'Amazonas', acronym: 'AM' },
    { estado: 'Bahia', acronym: 'BA' },
    { estado: 'Ceará', acronym: 'CE' },
    { estado: 'Distrito Federal', acronym: 'DF' },
    { estado: 'Espírito Santo', acronym: 'ES' },
    { estado: 'Goiás', acronym: 'GO' },
    { estado: 'Maranhão', acronym: 'MA' },
    { estado: 'Mato Grosso', acronym: 'MT' },
    { estado: 'Mato Grosso do Sul', acronym: 'MS' },
    { estado: 'Minas Gerais', acronym: 'MG' },
    { estado: 'Pará', acronym: 'PA' },
    { estado: 'Paraíba', acronym: 'PB' },
    { estado: 'Paraná', acronym: 'PR' },
    { estado: 'Pernambuco', acronym: 'PE' },
    { estado: 'Piauí', acronym: 'PI' },
    { estado: 'Rio de Janeiro', acronym: 'RJ' },
    { estado: 'Rio Grande do Norte', acronym: 'RN' },
    { estado: 'Rio Grande do Sul', acronym: 'RS' },
    { estado: 'Rondônia', acronym: 'RO' },
    { estado: 'Roraima', acronym: 'RR' },
    { estado: 'Santa Catarina', acronym: 'SC' },
    { estado: 'São Paulo', acronym: 'SP' },
    { estado: 'Sergipe', acronym: 'SE' },
    { estado: 'Tocantins', acronym: 'TO' }
];
